#page title
page_title                                : James Shaw | Milestones for Gumroad Creators                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1594575427                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Perfect Companion for Gumroad Creators to view real-time sales, transaction and product data.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : James Shaw
your_link                                 : https://shaw-james.com
your_city                                 : York, England
email_address                             :
facebook_username                         :
instagram_username                        : jsh8w
twitter_username                          : jsh8w
github_username                           : jsh8w
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Gumroad Revenue and Sales Dashboard
    description                           : View your live Gumroad revenue and sales data on your dashboard.
    fontawesome_icon_name                 : columns

  - title                                 : Sales, Transactions and Memberships Data
    description                           : View revenue reports for today, past month and all time.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Live Push Notifications for Sales
    description                           : Receive Push Notifications for real-time sales.
    fontawesome_icon_name                 : bell

  - title                                 : MRR Calculations
    description                           : See MRR Calculations for monthly, quarterly, biannually and yearly subscriptions.
    fontawesome_icon_name                 : infinity

  - title                                 : Product Listings
    description                           : Keep track of all your published/draft products on Gumroad.
    fontawesome_icon_name                 : shopping-cart

  - title                                 : FaceID Security
    description                           : FaceID/TouchID biometric security.
    fontawesome_icon_name                 : fingerprint



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#00acee"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#daa520"
feature_icons_background_color            : "#24223e"

social_icons_foreground_color             : "#daa520"
social_icons_background_color             : "#24223e"

footer_text_color                         : "#24223e"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
